---
# Ethereum network configuration
eth_network: "hoodi" # Options: mainnet, hoodi
execution_client: "geth" # Options: geth, reth
consensus_client: "lighthouse" # Options: lighthouse

# Client-specific versions
geth_version: "stable"

# User configuration
execution_user: "execution"
execution_group: "execution"

# Installation paths
data_dir: "/var/lib"
execution_dir: "{{ data_dir }}/execution"

# Service configurations

execution_exec: "{{ lookup('vars', execution_client + '_exec') }}"

geth_exec: |
  /usr/local/bin/geth \
    --{{ eth_network }} \
    --datadir {{ execution_dir }} \
    --port 30303 \
    --http.port 8545 \
    --authrpc.port 8551 \
    --maxpeers 50 \
    --metrics \
    --http \
    --pprof \
    --state.scheme=path \
    --authrpc.jwtsecret=/secrets/jwtsecret
