---
- name: Setup Ethereum Node
  hosts: ethereum_nodes
  become: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

  roles:
    - base
   # - ethereum
    - reth
    - lodestar
    - fail2ban
    - firewall
    - chrony
    - motd
