---
# UFW configuration
ufw_rules:
  - { port: 22, proto: tcp, comment: "SSH" }
  - { port: 30303, proto: tcp, comment: "Ethereum P2P TCP" }
  - { port: 30303, proto: udp, comment: "Ethereum P2P UDP" }
  - { port: 9000, proto: tcp, comment: "Lighthouse P2P" }
  - { port: 9001, proto: udp, comment: "Lighthouse QUIC" }

ufw_debian_packages:
  - ufw
