---

- name: Ensure required packages
  ansible.builtin.apt:
    pkg: "{{ ufw_debian_packages }}"
    state: present

- name: Configure UFW rules
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ ufw_rules }}"

- name: Enable UFW
  ansible.builtin.ufw:
    state: enabled
    policy: deny