- name: Configure Chrony
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    mode: '0644'

- name: Restart Chrony
  ansible.builtin.service:
    name: chrony
    state: restarted