---
# Check and display currently installed versions.
- name: Check if execution client (Geth) is installed
  ansible.builtin.shell: /usr/local/bin/geth version | grep ^Version | awk '{print $2}'
  register: geth_version
  changed_when: false
  failed_when: false
  when: execution_client == 'geth'

- name: Display installed versions
  ansible.builtin.debug:
    msg:
      - "------------------------------------"
      - "CURRENTLY INSTALLED VERSIONS"
      - "------------------------------------"
      - "Execution client ({{ execution_client }}): {{ geth_version.stdout | default(reth_version.stdout) | default('Not installed') }}"
      - "------------------------------------"

# Check for Geth updates
- name: Check for Geth updates
  when: execution_client == 'geth'
  block:
    - name: Get latest Geth version from download page
      ansible.builtin.shell: |
        RELEASE_URL="https://geth.ethereum.org/downloads"
        VERSION=$(curl -s $RELEASE_URL | grep -o "geth-linux-amd64-[0-9]\+\.[0-9]\+\.[0-9]\+" | head -1 | sed 's/geth-linux-amd64-//')
        echo $VERSION
      register: latest_geth_version
      changed_when: false
      failed_when: false

    - name: Compare installed and latest Geth versions
      ansible.builtin.debug:
        msg: |
          Installed Geth version: {{ execution_client_version.stdout | default('Not installed') }}
          Latest available version: {{ latest_geth_version.stdout | default('Unknown') }}
          {% if execution_client_version.stdout is defined and latest_geth_version.stdout is defined and execution_client_version.stdout != latest_geth_version.stdout %}
          Update available: Yes
          {% else %}
          Update available: No
          {% endif %}

- name: Display latest versions
  ansible.builtin.debug:
    msg:
      - "------------------------------------"
      - "LATEST AVAILABLE VERSIONS"
      - "------------------------------------"
      - "Execution client ({{ execution_client }}): {{ latest_geth_version.stdout | default(latest_reth_version.stdout) | default('Not installed') }}"
      - "------------------------------------"
