---
- name: Install security packages
  ansible.builtin.apt:
    name:
      - acl
      - unattended-upgrades
      - vim
      - ccze
      - tmux
      - git
      - jq
      - htop
      - curl
      - btop
      - vnstat
      - net-tools
      - iotop
      - iftop
      - iptraf-ng
    state: present

- name: Configure Unattended Upgrades
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: "0644"

- name: Enable Unattended Upgrades
  ansible.builtin.template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: "0644"
