---
- name: Check Ethereum Node Client Versions
  hosts: ethereum_nodes
  #become: true
  
  tasks:
    - name: Include role variables
      ansible.builtin.include_vars:
        dir: ../roles/ethereum/defaults
    
    - name: Check and display client versions
      ansible.builtin.include_tasks: ../roles/ethereum/tasks/version.yml 