name: Ansible Lint

on:
  push:
    branches: ["main", "stable", "release/*"]
    paths:
      - "roles/**"
      - "playbooks/**"
      - ".ansible-lint"
      - ".github/workflows/ansible-lint.yml"
  pull_request:
    branches: ["main", "stable", "release/*"]
    paths:
      - "roles/**"
      - "playbooks/**"
      - ".ansible-lint"
      - ".github/workflows/ansible-lint.yml"

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      contents: read
      security-events: write  # needed only for SARIF upload

    env:
      ANSIBLE_FORCE_COLOR: "1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          # If you have a dependency file, set cache and path like:
          # cache: "pip"
          # cache-dependency-path: |
          #   requirements*.txt
          #   pyproject.toml

      - name: Install ansible-lint
        run: |
          python -m pip install --upgrade pip
          pip install "ansible-lint[community]>=24.0.0"

      - name: Run ansible-lint (rich log)
        run: |
          ansible-lint --version
          ansible-lint --show-progress --format=rich | tee .ansible-lint.log
        continue-on-error: true  # keep going to still publish artifacts

      # Robust SARIF creation: always produce a file, even if lint fails or finds nothing.
      - name: Generate SARIF report
        run: |
          # Try native SARIF output to file
          if ansible-lint --format sarif -o ansible-lint.sarif ; then
            echo "SARIF generated by ansible-lint."
          else
            echo "ansible-lint exited non-zero; attempting to capture SARIF from stdout..."
            # Fallback: capture stdout to file so upload step has something
            ansible-lint --format sarif > ansible-lint.sarif || true
          fi
          # Ensure the file exists (even if empty) to avoid upload-step failures
          test -f ansible-lint.sarif || : > ansible-lint.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: hashFiles('ansible-lint.sarif') != ''
        with:
          sarif_file: ansible-lint.sarif

      - name: Upload lint results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ansible-lint-results
          path: |
            .ansible-lint-cache/
            .ansible-lint.log
            ansible-lint.sarif
          retention-days: 30
